import { Whisky } from "@/types";

// PRD docs/PRD.md 6-6. 추천 위스키 DB (30종 향미 벡터) 참고.
// flavor 점수는 0(거의 없음)~5(매우 강함) 스케일.
export const WHISKIES: Whisky[] = [
  {
    id: "glenfiddich-12",
    name: "Glenfiddich 12",
    nameKr: "글렌피딕 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 4, sherry: 1, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["크림치즈", "견과류", "가벼운 과일 디저트"],
    description:
      "배와 사과 같은 은은한 과일향과 부드러운 목넘김으로 세계에서 가장 많이 팔리는 싱글몰트 중 하나.",
    oneLiner: "위스키 첫 잔으로 실패할 확률이 가장 낮은 선택.",
  },
  {
    id: "glenlivet-12",
    name: "Glenlivet 12",
    nameKr: "글렌리벳 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 2, fruit: 4, sherry: 1, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["카나페", "산뜻한 샐러드", "가벼운 치즈"],
    description: "화사한 꽃향과 사과·배 향이 도드라지는 스페이사이드 대표 라이트 싱글몰트.",
    oneLiner: "산뜻하고 깔끔한 첫인상을 원한다면 정답.",
  },
  {
    id: "glenmorangie-original-10",
    name: "Glenmorangie Original 10",
    nameKr: "글렌모렌지 오리지널 10년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 2, fruit: 4, sherry: 1, vanilla: 3, spice: 1, body: 1 },
    pairingFood: ["복숭아 타르트", "바닐라 아이스크림", "가벼운 디저트"],
    description: "가장 높은 증류기로 만들어 유독 가볍고 화사한, 시트러스와 바닐라가 어우러진 향.",
    oneLiner: "가볍고 향긋한 위스키를 찾는다면 딱이에요.",
  },
  {
    id: "glenmorangie-lasanta",
    name: "Glenmorangie Lasanta",
    nameKr: "글렌모렌지 라산타",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 46,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 2, sherry: 4, vanilla: 3, spice: 2, body: 2 },
    pairingFood: ["다크초콜릿", "건과일", "캐러멜 디저트"],
    description: "올로로소 셰리 캐스크에서 추가 숙성해 건포도와 캐러멜의 달콤함을 더한 스타일.",
    oneLiner: "달콤함에 진한 여운까지, 디저트 같은 위스키.",
  },
  {
    id: "macallan-12-sherry-oak",
    name: "Macallan 12 Sherry Oak",
    nameKr: "맥캘란 12년 셰리 오크",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "프리미엄",
    difficulty: "쉬움",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 3, sherry: 5, vanilla: 2, spice: 2, body: 3 },
    pairingFood: ["다크초콜릿", "건포도", "치즈 플래터"],
    description: "100% 셰리 캐스크 숙성으로 건과일과 다크초콜릿의 묵직하고 진한 단맛이 특징.",
    oneLiner: "달달하고 묵직한 첫 위스키를 원한다면, 무조건 여기서 시작하세요.",
  },
  {
    id: "balvenie-12-doublewood",
    name: "Balvenie 12 Doublewood",
    nameKr: "발베니 12년 더블우드",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 2, sherry: 3, vanilla: 4, spice: 1, body: 2 },
    pairingFood: ["허니 카스텔라", "크렘브륄레", "견과류"],
    description: "버번 캐스크에서 숙성 후 셰리 캐스크에서 마무리, 허니와 바닐라의 부드러운 단맛.",
    oneLiner: "부드럽고 크리미한 목넘김에 반하게 되는 위스키.",
  },
  {
    id: "aberlour-12-double-cask",
    name: "Aberlour 12 Double Cask",
    nameKr: "아벨라워 12년 더블캐스크",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 2, sherry: 4, vanilla: 2, spice: 3, body: 2 },
    pairingFood: ["애플파이", "다크초콜릿", "말린 자두"],
    description: "셰리와 버번 캐스크를 함께 사용해 달콤함과 시나몬 같은 스파이스가 함께 느껴짐.",
    oneLiner: "달콤함에 스파이시한 포인트를 더한 균형잡힌 한 잔.",
  },
  {
    id: "dalmore-12",
    name: "Dalmore 12",
    nameKr: "달모어 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "프리미엄",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 3, sherry: 5, vanilla: 2, spice: 2, body: 3 },
    pairingFood: ["오렌지 초콜릿", "다크초콜릿", "치즈케이크"],
    description: "올로로소 셰리 캐스크 숙성으로 오렌지 껍질과 다크초콜릿의 묵직한 풍미가 도드라짐.",
    oneLiner: "진하고 고급스러운 셰리 풍미를 제대로 느끼고 싶을 때.",
  },
  {
    id: "highland-park-12",
    name: "Highland Park 12",
    nameKr: "하이랜드 파크 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 2, sweet: 3, fruit: 2, sherry: 2, vanilla: 2, spice: 2, body: 2 },
    pairingFood: ["훈제 연어", "허니 브레드", "견과류"],
    description: "은은한 피트와 헤더 꿀 향이 조화를 이루는 오크니 제도의 밸런스형 위스키.",
    oneLiner: "스모키함과 달콤함, 둘 다 조금씩 원한다면.",
  },
  {
    id: "bowmore-12",
    name: "Bowmore 12",
    nameKr: "보모어 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 3, sweet: 3, fruit: 3, sherry: 2, vanilla: 2, spice: 1, body: 2 },
    pairingFood: ["훈제 치즈", "레몬 타르트", "훈제 오리"],
    description: "아일라 위스키 중 상대적으로 부드러운 피트에 시트러스와 꿀 향이 더해진 스타일.",
    oneLiner: "피트 위스키에 처음 도전하고 싶다면 이걸로.",
  },
  {
    id: "talisker-10",
    name: "Talisker 10",
    nameKr: "탈리스커 10년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 45.8,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 3, sweet: 1, fruit: 1, sherry: 1, vanilla: 1, spice: 4, body: 4 },
    pairingFood: ["훈제 굴", "블루치즈", "매콤한 해산물"],
    description: "스카이섬 특유의 짠 바다 내음과 후추 같은 스파이시함, 묵직한 바디감이 특징.",
    oneLiner: "짠맛과 스파이시함이 폭발하는 바다 사나이 스타일.",
  },
  {
    id: "ardbeg-10",
    name: "Ardbeg 10",
    nameKr: "아드벡 10년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 46,
    priceTier: "일반",
    difficulty: "도전",
    highballFriendly: false,
    flavor: { peat: 5, sweet: 1, fruit: 3, sherry: 0, vanilla: 1, spice: 2, body: 3 },
    pairingFood: ["훈제 삼겹살", "블루치즈", "다크초콜릿"],
    description: "강렬한 피트향 속에 은근한 시트러스가 숨어있는 아일라 헤비 피트의 정석.",
    oneLiner: "스모키함에 자신 있다면, 확실하게 취향을 저격당할 것.",
  },
  {
    id: "laphroaig-10",
    name: "Laphroaig 10",
    nameKr: "라프로익 10년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "도전",
    highballFriendly: false,
    flavor: { peat: 5, sweet: 0, fruit: 1, sherry: 0, vanilla: 0, spice: 2, body: 4 },
    pairingFood: ["훈제 오징어", "블루치즈", "요오드향 해산물"],
    description: "소독약/의약품에 비유되는 강렬한 요오드-피트 향으로 유명한 아일라 위스키의 상징.",
    oneLiner: "위스키 애호가들이 '진짜 피트'를 말할 때 첫손에 꼽는 술.",
  },
  {
    id: "lagavulin-16",
    name: "Lagavulin 16",
    nameKr: "라가불린 16년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 43,
    priceTier: "프리미엄",
    difficulty: "도전",
    highballFriendly: false,
    flavor: { peat: 5, sweet: 2, fruit: 1, sherry: 3, vanilla: 1, spice: 2, body: 4 },
    pairingFood: ["훈제 갈비", "다크초콜릿", "숙성 치즈"],
    description: "강렬한 피트에 셰리의 단맛과 묵직함이 더해져 깊고 복합적인 여운을 남기는 아일라 명작.",
    oneLiner: "묵직한 피트와 셰리의 조화, 애호가들의 만장일치 명작.",
  },
  {
    id: "monkey-shoulder",
    name: "Monkey Shoulder",
    nameKr: "몽키 숄더",
    country: "스코틀랜드",
    type: "블렌디드몰트",
    abv: 40,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 3, sherry: 1, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["육포", "감자칩", "가벼운 안주"],
    description: "3종 싱글몰트를 블렌딩해 가볍고 달콤하게 만든, 하이볼로 마시기 최적화된 위스키.",
    oneLiner: "하이볼용으로 사둬도 절대 손해 없는 가성비 위스키.",
  },
  {
    id: "johnnie-walker-black",
    name: "Johnnie Walker Black",
    nameKr: "조니워커 블랙",
    country: "스코틀랜드",
    type: "블렌디드",
    abv: 40,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 2, sweet: 3, fruit: 2, sherry: 2, vanilla: 2, spice: 2, body: 2 },
    pairingFood: ["육포", "피자", "훈제 치즈"],
    description: "은은한 스모키함과 달콤함이 균형을 이루는, 어디서나 구하기 쉬운 스테디셀러 블렌디드.",
    oneLiner: "어느 바에서나 실패 없는, 만능 스테디셀러.",
  },
  {
    id: "chivas-regal-12",
    name: "Chivas Regal 12",
    nameKr: "시바스 리갈 12년",
    country: "스코틀랜드",
    type: "블렌디드",
    abv: 40,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 3, sherry: 2, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["카나페", "가벼운 치즈", "과일 안주"],
    description: "부드럽고 매끈한 목넘김에 사과와 꿀 향이 어우러진, 편안하게 마시기 좋은 블렌디드.",
    oneLiner: "부드럽고 무난해서 누구에게 선물해도 좋은 한 병.",
  },
  {
    id: "jameson",
    name: "Jameson",
    nameKr: "제임슨",
    country: "아일랜드",
    type: "블렌디드",
    abv: 40,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 2, fruit: 3, sherry: 1, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["피자", "감자튀김", "가벼운 안주"],
    description: "3회 증류로 유독 부드럽고 가벼운, 하이볼과 온더락 모두에서 편하게 즐기는 아이리시 위스키.",
    oneLiner: "가볍고 부담 없이, 매일 마셔도 질리지 않는 스타일.",
  },
  {
    id: "suntory-toki",
    name: "Suntory Toki",
    nameKr: "산토리 토키",
    country: "일본",
    type: "블렌디드",
    abv: 43,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 2, fruit: 4, sherry: 1, vanilla: 2, spice: 1, body: 1 },
    pairingFood: ["가벼운 안주", "회", "과일"],
    description: "청사과와 꿀 향이 산뜻하게 느껴지는, 하이볼 전용으로 개발된 일본 블렌디드 위스키.",
    oneLiner: "하이볼 마니아라면 반드시 거쳐가야 할 필수 코스.",
  },
  {
    id: "hibiki-harmony",
    name: "Hibiki Harmony",
    nameKr: "히비키 하모니",
    country: "일본",
    type: "블렌디드",
    abv: 43,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 4, sherry: 2, vanilla: 3, spice: 1, body: 2 },
    pairingFood: ["초밥", "가벼운 디저트", "과일"],
    description: "장미 같은 화사한 향과 오렌지 마멀레이드의 은은한 단맛이 조화로운 우아한 블렌디드.",
    oneLiner: "화사하고 우아한, 선물하기 딱 좋은 한 병.",
  },
  {
    id: "macallan-double-cask-12",
    name: "Macallan Double Cask 12",
    nameKr: "맥캘란 더블캐스크 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 4, fruit: 3, sherry: 3, vanilla: 3, spice: 2, body: 2 },
    pairingFood: ["바닐라 디저트", "생강쿠키", "건과일"],
    description: "셰리 오크와 버번 오크를 함께 사용해 셰리 오크보다 가볍고 생강향이 도는 달콤한 스타일.",
    oneLiner: "셰리 특유의 진함이 부담스럽다면 이쪽으로.",
  },
  {
    id: "glenfarclas-12",
    name: "Glenfarclas 12",
    nameKr: "글렌파클라스 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 43,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 0, sweet: 3, fruit: 2, sherry: 4, vanilla: 2, spice: 3, body: 3 },
    pairingFood: ["건포도", "다크초콜릿", "스파이스 쿠키"],
    description: "100% 셰리 캐스크 숙성 가문 소유 증류소로, 묵직한 몰트감과 스파이시한 여운이 특징.",
    oneLiner: "셰리 위스키 중에서도 묵직하고 진한 걸 찾는다면.",
  },
  {
    id: "benriach-the-twelve",
    name: "BenRiach The Twelve",
    nameKr: "벤리악 더 트웰브",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 43,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 4, sherry: 2, vanilla: 3, spice: 2, body: 2 },
    pairingFood: ["복숭아 파이", "허니 토스트", "견과류"],
    description: "버번, 셰리, 버진오크 등 다양한 캐스크를 블렌딩해 꿀과 과일향이 풍부한 스타일.",
    oneLiner: "다채로운 과일향을 부담 없이 즐기고 싶을 때.",
  },
  {
    id: "auchentoshan-12",
    name: "Auchentoshan 12",
    nameKr: "오켄토션 12년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 40,
    priceTier: "가성비",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 2, fruit: 3, sherry: 1, vanilla: 3, spice: 1, body: 1 },
    pairingFood: ["가벼운 카나페", "레몬 디저트", "과일"],
    description: "스코틀랜드에서 드문 3회 증류 방식으로 만들어 유독 가볍고 부드러운 로우랜드 위스키.",
    oneLiner: "가장 가볍고 부드러운 스코치를 찾는다면 여기.",
  },
  {
    id: "springbank-10",
    name: "Springbank 10",
    nameKr: "스프링뱅크 10년",
    country: "스코틀랜드",
    type: "싱글몰트",
    abv: 46,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 2, sweet: 2, fruit: 3, sherry: 1, vanilla: 1, spice: 2, body: 3 },
    pairingFood: ["훈제 굴", "레몬을 곁들인 해산물", "짠맛 안주"],
    description: "은은한 피트와 짠 바다향, 독특한 오일리 질감이 매력적인 캠벨타운의 개성파 위스키.",
    oneLiner: "평범한 향미가 지겨워졌을 때 도전해볼 만한 개성파.",
  },
  {
    id: "johnnie-walker-green-15",
    name: "Johnnie Walker Green Label 15",
    nameKr: "조니워커 그린 라벨 15년",
    country: "스코틀랜드",
    type: "블렌디드몰트",
    abv: 43,
    priceTier: "프리미엄",
    difficulty: "중간",
    highballFriendly: false,
    flavor: { peat: 3, sweet: 2, fruit: 3, sherry: 1, vanilla: 2, spice: 2, body: 3 },
    pairingFood: ["훈제 치즈", "견과류", "다크초콜릿"],
    description: "탈리스커, 크래겐모어 등 4종의 싱글몰트만을 블렌딩해 스모키함과 과일향이 복합적으로 어우러짐.",
    oneLiner: "블렌디드지만 싱글몰트 못지않은 복합미를 원할 때.",
  },
  {
    id: "kavalan-classic",
    name: "Kavalan Classic",
    nameKr: "카바란 클래식",
    country: "대만",
    type: "싱글몰트",
    abv: 40,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 4, fruit: 5, sherry: 1, vanilla: 4, spice: 1, body: 2 },
    pairingFood: ["망고", "파인애플", "바닐라 디저트"],
    description: "더운 기후에서 빠르게 숙성돼 망고·파인애플 같은 트로피컬 과일향이 폭발적으로 느껴짐.",
    oneLiner: "과일향 폭탄, 이거 마시고 위스키 사랑에 빠지는 사람 많아요.",
  },
  {
    id: "yamazaki-12",
    name: "Yamazaki 12",
    nameKr: "야마자키 12년",
    country: "일본",
    type: "싱글몰트",
    abv: 43,
    priceTier: "프리미엄",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 3, fruit: 4, sherry: 2, vanilla: 3, spice: 2, body: 2 },
    pairingFood: ["복숭아", "초밥", "가벼운 디저트"],
    description: "미즈나라 오크에서 오는 은은한 백단향과 복숭아 같은 과일향이 조화로운 일본 대표 싱글몰트.",
    oneLiner: "우아하고 섬세한 첫 프리미엄 위스키로 제격.",
  },
  {
    id: "nikka-from-the-barrel",
    name: "Nikka From The Barrel",
    nameKr: "니카 프롬 더 배럴",
    country: "일본",
    type: "블렌디드",
    abv: 51.4,
    priceTier: "일반",
    difficulty: "중간",
    highballFriendly: true,
    flavor: { peat: 1, sweet: 3, fruit: 3, sherry: 2, vanilla: 2, spice: 3, body: 4 },
    pairingFood: ["오렌지 껍질 초콜릿", "훈제 치즈", "매콤한 안주"],
    description: "여러 원액을 병에서 한 번 더 블렌딩해 높은 도수에도 진하고 복합적인 풍미를 자랑하는 위스키.",
    oneLiner: "진하게 마셔도, 하이볼로 마셔도 존재감이 확실한 위스키.",
  },
  {
    id: "woodford-reserve",
    name: "Woodford Reserve",
    nameKr: "우드포드 리저브",
    country: "미국",
    type: "버번",
    abv: 43.2,
    priceTier: "일반",
    difficulty: "쉬움",
    highballFriendly: true,
    flavor: { peat: 0, sweet: 4, fruit: 2, sherry: 2, vanilla: 4, spice: 3, body: 3 },
    pairingFood: ["바닐라 아이스크림", "피칸파이", "그릴 스테이크"],
    description: "옥수수 베이스의 묵직한 단맛에 시나몬·바닐라 향이 진하게 퍼지는 미국 대표 버번.",
    oneLiner: "스코치와는 다른 매력, 진하고 달콤한 버번의 정석.",
  },
];

export function getWhiskyById(id: string): Whisky | undefined {
  return WHISKIES.find((whisky) => whisky.id === id);
}
